version: '3'
services:
  next:
    build:
      context: ./docker/next
      dockerfile: Dockerfile
    ports:
      - 3030:3000
    volumes:
      - ./app/next:/app:cached
      # exclude volumes
      - /app/next/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
